package com.zackmon99.android.libLifeConnect
class LibLifeConnect {
    companion object {
        const val NEWGAME = "<ACTION:NEWGAME>"
        const val UPDATEPLAYER = "<ACTION:UPDATEPLAYER>"
        const val CONNECT = "<ACTION:CONNECT>"
        const val MODIFYLIFEREQUEST = "<ACTION:MODIFYLIFEREQUEST>"
        const val MODIFYPOISONREQUEST = "<ACTION:MODIFYPOISONREQUEST>"
        const val MODIFYCOMMANDERDAMAGEREQUEST = "<ACTION:MODIFYCOMMANDERDAMAGEREQUEST>"
        const val MODIFYPLAYERNAMEREQUEST = "<ACTION:MODIFYPLAYERNAMEREQUEST>"
        const val MODIFYCOMMANDERNAMEREQUEST = "<ACTION:MODIFYCOMMANDERNAMEREQUEST>"
        const val MODIFYPARTNERCOMMANDERREQUEST = "<ACTION:MODIFYPARTNERCOMMANDERREQUEST>"
    }
}